### ISSUE TITLE
It's not documented HOW to use this with git-lablel or git-label-cli

### ISSUE THREAD

**Issue by Relequestual** [jasonbellamy/git-label-packages#10]
I'd like to use git-label-cli to setup the labels found in some of these packages.
It's not clear how to do this at all. The readme says it is possible but not how.

**Comment by aidabeorn** [comment]
It's covered in this medium post for example: https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63

**Comment by Relequestual** [comment]
That's git-labelmaker, not git-label-cli.
Thanks though.

**Comment by jasonbellamy** [comment]
@Relequestual [git-label-cli](https://github.com/jasonbellamy/git-label-cli) accepts a `-p/--pattern` flag that allows you to specify the location of label package(s) to use via a globbing pattern.

```bash
git-label-cli -p ./location/of/packages/*.json
```
