### ISSUE TITLE
Table flip label

### ISSUE THREAD

**Issue by himynameisdave** [jasonbellamy/git-label-packages#6]
Why isn't `(ノಠ益ಠ)ノ彡┻━┻` a default label? This is high priority lets get on this thing asap :100:

**Comment by mrbaguettefr** [comment]
https://github.com/himynameisdave/git-label-faces

**Comment by jasonbellamy** [comment]
Closed via https://github.com/himynameisdave/git-label-faces/commit/ced3bf34bf81247beb5840a8be4da06440390ec5
